// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./components/Background/index.tsx')['default']
    Button: typeof import('./components/Button/index.tsx')['default']
    Card: typeof import('./views/Home/part3/Card/index.tsx')['default']
    Carousel: typeof import('./views/Home/Part2/Carousel/index.tsx')['default']
    CHeader: typeof import('./components/CHeader/index.vue')['default']
    CHeaderInner: typeof import('./components/CHeaderInner/index.vue')['default']
    Circle: typeof import('./components/Circle/index.tsx')['default']
    CLayout: typeof import('./components/CLayout/index.vue')['default']
    DCard: typeof import('./components/DCard/index.tsx')['default']
    DForm: typeof import('./components/DForm/index.tsx')['default']
    Dialog: typeof import('./components/Dialog/index.tsx')['default']
    DImage: typeof import('./components/DImage/index.tsx')['default']
    Document: typeof import('./components/Document/index.tsx')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Form: typeof import('./components/DForm/index.tsx')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFiles: typeof import('~icons/ep/files')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    Image: typeof import('./components/Image/index.tsx')['default']
    Indedx: typeof import('./components/DCard/indedx.tsx')['default']
    Input: typeof import('./components/Input/index.tsx')['default']
    Introduction: typeof import('./views/Home/Part1/Introduction/index.tsx')['default']
    Layout: typeof import('./components/Layout/index.tsx')['default']
    LocCard: typeof import('./components/LocCard/index.tsx')['default']
    Logo: typeof import('./components/logo/index.tsx')['default']
    Menu: typeof import('./views/Menu/index.tsx')['default']
    NoShowMob: typeof import('./components/NoShowMob/index.tsx')['default']
    NotShowMobile: typeof import('./components/NotShowMobile/index.tsx')['default']
    QuestionsCop: typeof import('./components/QuestionsCop/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./views/Menu/TextButton/index.tsx')['default']
    Title: typeof import('./views/Home/Part1/Introduction/Title/index.tsx')['default']
    Trans: typeof import('./components/Trans/index.tsx')['default']
  }
}
